name: CI

on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  lint-local:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: pip install tox
      - run: tox -e flake8

  build:
    runs-on: ubuntu-18.04
    env:
      CI_BUILD_WHEEL: 1
      CI_BUILD_PYINSTALLER: 1
      CI_BUILD_WININSTALLER: 0
      CI_BUILD_DOCKER: 1
      CI_BUILD_KEY: ${{ secrets.CI_BUILD_KEY }}
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - if: matrix.platform == 'windows'
        uses: actions/cache@v2
        with:
          path: release/installbuilder/setup
          key: installbuilder
      - run: pip install -e .[dev]
      - run: python release/cibuild.py build
      - uses: docker/setup-qemu-action@27d0a4f181a40b142cce983c5393082c365d1480
      - uses: docker/setup-buildx-action@b1f1f719c7cd5364be7c82e366366da322d01f7c
      - run: python release/cibuild.py build_image



